### ISSUE TITLE
Clean up stuff

### ISSUE THREAD

**Issue by eliaslfox** [eliaslfox/language-elm#1]
* add links to the github and hackage page in the readme
* run tests on the place (travis)
* have coverage
* add badges

**Comment by purcell** [comment]
Just came across this library - thanks! - and maybe this issue is a good place to note that the `Decleration` module name is misspelt, and should instead be `Declaration`.

**Comment by eliaslfox** [comment]
Thanks for letting me know. I guess I really should get spellcheck working in vim.

I'll release a new version with a fix as soon as I can.

**Comment by eliaslfox** [comment]
This is fixed by #5
